name: CI Workflow

on:
 push:
   branches:
     - main

jobs:
 build-test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Code
       uses: actions/checkout@v3
     - name: List files for debugging
       run: ls -la  # This will list the files in the current directory to verify package.json exists.
     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
         node-version: 18

     - name: Install Dependencies
       run: npm install

     - name: Run Tests
       run: npm test

 build-publish:
   needs: build-test
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}

     - name: Build and Push Docker Image
       uses: docker/build-push-action@v4
       with:
         context: .
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/cpsy-350-ci-base:latest
